### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by 15536500918** [XMUDM/SentiWSP#2]
万分感谢！

**Comment by Fans-xmu** [comment]
已更新

**Comment by 15536500918** [comment]
非常感谢，祝您一切顺利！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Nov 18, 2022 11:04 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [XMUDM/SentiWSP] 您好，我是一位研一的学生，这段时间阅读了您的这篇论文，想实现一下模型，发现似乎存在一些问题，里面的utils等地方似乎没有，想问下您能否发一下完整代码，我将不胜感激！ (Issue #2)

&nbsp;



 
已更新

**Comment by 15536500918** [comment]
很抱歉再次打扰您。今天，我尝试了该代码，首先我运行pretrain_word.py,目前发生了几个错误，想请教下您，十分感谢。
1：（47行）
print("now mask prob",args.mask_prob)
AttributeError:'Namespace' object has no attritude 'mask prob'
2:(61行）
torch.distributed.init process group(backend=”nccl”)
ValueError:Error initializing torch.distributed using env://rendezvous:environment variable RANK expected,but not set
3:(327-329行)
generator_size_divisor均标红。
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Nov 18, 2022 11:06 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [XMUDM/SentiWSP] QA (Issue #2)

&nbsp;



 
Closed #2 as completed.
